version: "3"

services:

  mongo:
    image: mongo
    ports: 
      - "27017:27017" 

  app:
    container_name: appnode
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo