version: "3"

services:

  mongo:
    container_name: mongo
    image: mongo
    ports: 
      - "27018:27017" 

  app:
    container_name: appnode
    image: imgshare
    ports:
      - "3001:3000"
    depends_on:
      - mongo